default_language_version:
    python: python3

repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.2.2"
    hooks:
      - id: pycln

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md] # Do not process Markdown files.
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-builtin-literals

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        additional_dependencies: [
          "git+https://github.com/RedHatQE/flake8-plugins.git",
          "pep8-naming",
          "flake8-mutable",
        ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    - id: markdownlint
      args: [--fix]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: [--fix]
