# All ${} taken from .env file, create .env file in root of project.
version: "3.8"
services:
  github_webhook_server:
    container_name: github_webhook_server
    build: webhook-server-container
    volumes:
      - ./config.yaml:/config.yaml:Z
      - .tox-results:/tox-results
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
    environment:
      - FLASK_DEBUG=1 # Debug Flask server to get logs to console.
    ports:
      - "5000:5000"
    privileged: true
    restart: unless-stopped
