services:
  github-webhook-server:
    container_name: github-webhook-server
    build: webhook-server-container
      - ./webhook_server_data_dir:/webhook_server:Z # Should include config.yaml and webhook-server.private-key.pem
      - ./containers:/containers:Z # optional, to cache podman pull containers
    environment:
      - WEBHOOK_SERVER_LOG_FILE=/tmp/webhook_server.log
      - FLASK_DEBUG=1 # Debug Flask server to get logs to console.
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - DEVELOPMENT=false # Set to true when developing.
    ports:
      - "5000:5000"
    privileged: true
    restart: unless-stopped
