repositories:
  openshift-python-wrapper:
    type: github
    webhook_ip: <HTTP://IP OR URL:PORT>
    name: RedHatQE/openshift-python-wrapper
    token: <GITHIB TOKEN>
    verified_job: true
    pypi:
      token: <PYPI TOKEN>
      tool: <poetry or twine>
    events:  # To listen to all events do not send events
      - push
      - pull_request
      - issue_comment
    tox: all # Run all tests in tox.ini
    protected-branches:
      main:
        - "pre-commit.ci - pr"
        - "WIP"
    container:
      username: <registry username>
      passord: <registry_password>
      repository: <registry_repository_full_path>
      tag: <image_tag>
