github-app-id: 123456 # GitHub app id
github-toekn: <GITHIB TOKEN>
webhook_ip: <HTTP://IP OR URL:PORT>

sonarqube:
  url: <SonaQube URL>
  token: <SonaQube token>

docker: # Used to pull images from docker.io
  username: <username>
  password: <password>

default-status-checks:
  - "WIP"
  - "dpulls"
  - "Inclusive Language",
  - "can-be-merged"

repositories:
  my-repository:
    name: my-org/my-repository
    slack_webhook_url: <Slack webhook url> # Send notification to slack on several operations
    verified_job: true
    sonarqube: true
    pypi:
      token: <PYPI TOKEN>
    events:  # To listen to all events do not send events
      - push
      - pull_request
      - issue_comment
    tox: all # Run all tests in tox.ini
    protected-branches:
      dev: []
      main: # set [] in order to set all defaults run included
        include-runs:
          - "pre-commit.ci - pr"
          - "WIP"
        exclude-runs:
          - "SonarCloud Code Analysis"
    container:
      username: <registry username>
      password: <registry_password>
      repository: <registry_repository_full_path>
      tag: <image_tag>
      build-args: # build args to send to podman build command
        - build-arg1=1
        - build-arg2=2
      args: # args to send to podman build command
        - --format docker
