repositories:
  # GITHUB repositories example
  openshift-python-wrapper:
    type: github
    webhook_ip: <HTTP://IP OR URL:PORT>
    name: RedHatQE/openshift-python-wrapper
    token: <GITHIB TOKEN>
    verified_job: true
    pypi:
      token: <PYPI TOKEN>
      tool: <poetry or twine>
    events:  # To listen to all events do not send events
      - push
      - pull_request
      - issue_comment
    tox: all # Run all tests in tox.ini

  # GITLAB repositories example
  openshift-python-wrapper-2:
    type: gitlab
    webhook_ip: <HTTP://IP OR URL:PORT>
    name: RedHatQE/openshift-python-wrapper
    project_id: <PROJECT ID>
    events:
      - merge_requests_events
      - note_events
    tox: code-check,unused-code # Run only specific tests in tox.ini
