[tool.black]
line-length = 88
target_version = ['py37', 'py38', 'py39', 'py310', "py311"]
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
    | \.tox
  )/
)
'''

[tool.isort]
line_length = 88
profile = "black"

[tool.poetry]
name = "github-webhook-server"
version = "1.0.0"
description = "A webhook server to handle Github/Gitlab reposotories."
authors = ["Meni Yakove", "Ruth Netser"]
readme = "README.md"
repository = "https://github.com/myakove/github-webhook-server"

[tool.poetry.dependencies]
python = "^3.8"
poetry-dynamic-versioning = {extras = ["plugin"], version = "^0.25.0"}
pygithub = "^1.59.0"
flask = "^2.3.2"
pyyaml = "^6.0"
build = "^0.10.0"
twine = "^4.0.2"
tox = "^4.6.4"

[tool.poetry.dev-dependencies]
ipython = "*"
ipdb = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
